### ISSUE TITLE
Nothing Happens (details in post)

### ISSUE THREAD

**Issue by Vand3rz** [SuiMachine/AVP2-Custom-Launcher#9]
Game is crashing instantly without error message. It shows in Task Manager Processes for a second and then disappears. 

Downloaded the files and installed correctly.

Run as Admin selected and running in compatibility mode for Windows 98/Windows ME (otherwise Client MFC Application Stopped Working).
Only occurs when resolution set to one the game doesn't have by default. I have it set to 1920x1080.

Happens for both base game and Primal Hunt.

Running on Windows 7. Have all necessary software.

Suggestions please.

**Comment by SuiMachine** [comment]
Running Windows 98/Windows Me compatibility will only make things worse and if applied to LithTech.exe it will indeed make the game crash (not sure if it's addresses that change with some compatibility flags or is it threads or file paths - 98/Me compatibility profile is just way too bloated with crap).

**Comment by Vand3rz** [comment]
Unfortunately it crashes whether I run it in compatibility mode or not. I haven't touched the LithTech.exe though.

**Comment by SuiMachine** [comment]
OK, so first. Don't even try running a custom launcher with any compatibility (well you can try administrator I guess, if there are issues with DLL injection).
2nd - uncheck "Enable Aspect Ratio Fix" to disable DLL injection and then try launching the game. If it still crashes - it's something between your OS and the game (as in not really a fault of custom launcher). You can try to set the compatibility for LithTech.exe, but I'd probably recommend against using 98/Me, since for me it always crashes no matter how I try to run the game.
